"""
Auto-generated by IpumsCodebookParser.py
Variable : MOMLOC
JSON     : JSON/momloc_codes.json

Usage:
    from _get_momloc import get_momloc
    description = get_momloc(code)   # code can be int, float, or str
"""

import json
import os

# ---------------------------------------------------------------------------
# Load the code map once at import time
# ---------------------------------------------------------------------------
_MAP_PATH = os.path.join(os.path.dirname(__file__), '..', 'JSON', 'momloc_codes.json')
_MAP_PATH = os.path.normpath(_MAP_PATH)

_map  = {}
_width = 4

try:
    with open(_MAP_PATH, 'r', encoding='utf-8') as _f:
        _map = json.load(_f)
    if _map:
        _width = len(next(iter(_map)))
except FileNotFoundError:
    pass   # getter returns Unknown for all codes if JSON missing


# ---------------------------------------------------------------------------
# Public function
# ---------------------------------------------------------------------------

def get_momloc(code) -> str:
    """
    Return the description for a MOMLOC code.
    Accepts int, float, or str in any format.
    """
    if code is None:
        return 'Unknown (None)'

    # Normalize to a plain integer string, then zero-fill to the key width
    try:
        key = str(int(float(str(code)))).zfill(_width)
    except (ValueError, TypeError):
        return f'Unknown ({code!r})'

    return _map.get(key, f'Unknown ({code!r})')


# ---------------------------------------------------------------------------
# Quick self-test
# ---------------------------------------------------------------------------

if __name__ == '__main__':
    print(f"Testing _get_momloc")
    print(f"  JSON path : {_MAP_PATH}")
    print(f"  Key width : {_width}")
    print(f"  Codes loaded: {len(_map)}")
    print()

    if _map:
        first_key   = next(iter(_map))
        first_desc  = _map[first_key]
        first_int   = int(first_key)
        print(f"    Testing all input formats for key={first_key!r} ({first_desc}):")
        print(f"      get_momloc({first_int!r})        -> {get_momloc(first_int)}")
        print(f"      get_momloc({str(first_int)!r})     -> {get_momloc(str(first_int))}")
        print(f"      get_momloc({first_key!r})    -> {get_momloc(first_key)}")
        print(f"      get_momloc(float(first_int)) -> {get_momloc(float(first_int))}")
    else:
        print("    WARNING: no codes loaded -- check JSON path")
