
"""
-----------------------------------
File: _get_stateicp.py  (auto-generated by IpumsCodebookParser.py)

Summary: Data Access Layer for STATEICP codes.
         Accepts any numeric representation of the code:
         integer or string, with or without leading zeros.
         Key width (4 digits for STATEICP) is detected
         automatically from the JSON, so no hardcoding needed.
--------------------------------
"""
import json


# ---------------------------------------------------------------------------
# 1. CACHE -- loaded once at import time
# ---------------------------------------------------------------------------
_map   = {}          # code_string -> description
_width = 1            # key width detected from JSON (e.g. 1, 2, 3, 4)

_json_path = r"E:/Claude/JSON/stateicp_codes.json"

try:
    with open(_json_path, 'r', encoding='utf-8') as _f:
        _raw = json.load(_f)
    _map = _raw.get("STATEICP", _raw)
    _width = len(next(iter(_map))) if _map else 1
except FileNotFoundError:
    print(f"WARNING: {_json_path} not found -- STATEICP lookups will return Unknown")
except Exception as _e:
    print(f"WARNING: could not load STATEICP codes: {_e}")


# ---------------------------------------------------------------------------
# 2. GETTER
# ---------------------------------------------------------------------------
def get_stateicp(code):
    """
    Returns the description for a STATEICP code.

    Accepts: integer 70, string "70", "070", or "0070" -- all equivalent.
    Returns: description string, or "Unknown (<code>)" if not found.
    """
    try:
        normalized = str(int(str(code).strip())).zfill(_width)
    except (ValueError, TypeError):
        return f"Unknown ({code})"
    return _map.get(normalized, f"Unknown ({normalized})")


# ---------------------------------------------------------------------------
# 3. TEST BLOCK
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    print(f"--- Testing STATEICP Getter (key width = {_width}) ---")
    print(f"    JSON entries loaded: {len(_map)}")
    print()

    if _map:
        first_key = next(iter(_map))
        first_val = int(first_key)

        test_inputs = [
            first_val,
            str(first_val),
            first_key.lstrip("0") or "0",
            first_key,
        ]

        print(f"    Testing all input formats for key={first_key!r} ({_map[first_key]}):")
        for t in test_inputs:
            result = get_stateicp(t)
            print(f"      get_stateicp({t!r:>8}) -> {result}")
    else:
        print("    No data loaded -- check JSON path.")
