"""
-----------------------------------
File: ftm_report_to_csv.py

Summary: Parses the structured gedcom_individuals.csv file generated by Claude
         and flattens it into a tabular CSV.
         Bridges Husbands and Wives onto the exact same row to create the 
         12-Variable Couple Fingerprint (now including Birth Month and Marriage Year).

Architect & Designer: Andy Askey
Coders (AI Assistants): Google Gemini, Anthropic Claude, Gemini Code Assist

License: Apache License 2.0 http://www.apache.org/licenses/LICENSE-2.0
-----------------------------------
"""

import csv
import os
import re
import sys

script_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.abspath(os.path.join(script_dir, '..', '..'))
for p in [os.path.join(project_root, 'python'), project_root]:
    if p not in sys.path:
        sys.path.append(p)

from utils import gen_logging


def extract_state(loc_str):
    """Strips city/county and returns only the state/country name."""
    if not loc_str: return ""
    loc_lower = loc_str.lower()
    states = [
        "alabama", "alaska", "arizona", "arkansas", "california", "colorado", "connecticut",
        "delaware", "district of columbia", "florida", "georgia", "hawaii", "idaho", "illinois",
        "indiana", "iowa", "kansas", "kentucky", "louisiana", "maine", "maryland", "massachusetts",
        "michigan", "minnesota", "mississippi", "missouri", "montana", "nebraska", "nevada", "new hampshire",
        "new jersey", "new mexico", "new york", "north carolina", "north dakota", "ohio", "oklahoma", "oregon",
        "pennsylvania", "rhode island", "south carolina", "south dakota", "tennessee", "texas",
        "utah", "vermont", "virginia", "washington", "west virginia", "wisconsin", "wyoming",
        "england", "scotland", "wales", "ireland", "northern ireland", "germany", "sweden", "norway",
        "denmark", "netherlands", "france", "switzerland", "canada", "mexico", "japan", "south korea"
    ]
    for s in states:
        if s in loc_lower:
            if s == "district of columbia": return "District of Columbia"
            return s.title()
    return loc_str.strip()


def split_name(full_name):
    """Safely splits a string into first/middle and last names, handling suffixes."""
    tokens = full_name.replace(',', '').strip().split()
    if not tokens: return "", ""
    if len(tokens) == 1: return tokens[0], ""

    suffixes = {'jr', 'jr.', 'sr', 'sr.', 'ii', 'iii', 'iv', 'v'}
    if len(tokens) >= 3 and tokens[-1].lower() in suffixes:
        return " ".join(tokens[:-2]), f"{tokens[-2]} {tokens[-1]}"

    return " ".join(tokens[:-1]), tokens[-1]


def parse_date(date_str):
    """Extracts a 4-digit year and the month number from a date string."""
    if not date_str:
        return "", ""
    date_str = str(date_str).upper()
    byr_match = re.search(r'\b(1[456789]\d\d|20\d\d)\b', date_str)
    byr = byr_match.group(1) if byr_match else ""

    bmo = ""
    months = ["JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"]
    for i, m in enumerate(months, 1):
        if m in date_str:
            bmo = str(i)
            break

    return byr, bmo


def find_person(name, byr_str, people_by_name):
    """Looks up a person in the dictionary by name and (optionally) birth year."""
    if not name or name not in people_by_name:
        return None
    candidates = people_by_name[name]
    if len(candidates) == 1:
        return candidates[0]

    target_byr, _ = parse_date(byr_str)
    for c in candidates:
        c_byr, _ = parse_date(c.get('Birth Date', ''))
        if c_byr == target_byr:
            return c
    return candidates[0]


def convert_gedcom_csv(input_csv, couples_csv, logger):
    if not os.path.exists(input_csv):
        logger.error(f"Cannot find input file: {input_csv}")
        return

    logger.info(f"Parsing structured GEDCOM CSV report: {input_csv}")

    people_by_name = {}

    with open(input_csv, 'r', encoding='utf-8', errors='replace') as f:
        reader = csv.DictReader(f)
        for row in reader:
            first = row.get('First Name', '').strip()
            last = row.get('Last Name', '').strip()
            if not last or '--' in last or 'Hidden' in last or '[' in last:
                continue

            name_key = f"{first} {last}".strip()
            if name_key not in people_by_name:
                people_by_name[name_key] = []
            people_by_name[name_key].append(row)

    records = []
    seen_couples = set()

    with open(input_csv, 'r', encoding='utf-8', errors='replace') as f:
        reader = csv.DictReader(f)
        for row in reader:
            p1_first = row.get('First Name', '').strip()
            p1_last = row.get('Last Name', '').strip()
            if not p1_last or '--' in p1_last or 'Hidden' in p1_last or '[' in p1_last:
                continue

            p1_sex = row.get('Sex', '').strip().upper()
            p1_byr, p1_bmo = parse_date(row.get('Birth Date', ''))
            p1_bpl = extract_state(row.get('Birth Place', ''))
            p1_fbpl = extract_state(row.get('Father Birth Place', ''))
            p1_mbpl = extract_state(row.get('Mother Birth Place', ''))

            spouses_str = row.get('Spouse(s)', '')

            # We ONLY process couples from the Husband's perspective to avoid duplicates,
            # UNLESS it's a Lone Wolf Female.
            if spouses_str and p1_sex == 'M':
                spouses = [s.strip() for s in spouses_str.split('|')]
                sp_byrs_str = [s.strip() for s in row.get('Spouse Birth Year(s)', '').split('|')]
                sp_bpls_str = [s.strip() for s in row.get('Spouse Birth Place(s)', '').split('|')]
                marr_dates = [s.strip() for s in row.get('Marriage Date(s)', '').split('|')]

                children_str = row.get('Children', '').strip()
                num_children_str = str(row.get('Num Children', '')).strip()

                if num_children_str.isdigit():
                    num_children = int(num_children_str)
                else:
                    num_children = len([c for c in children_str.split('|') if c.strip()]) if children_str else 0

                for i, sp_name in enumerate(spouses):
                    if not sp_name:
                        continue

                    sp_byr_fallback = sp_byrs_str[i].strip() if i < len(sp_byrs_str) else ""
                    sp_bpl_fallback = sp_bpls_str[i].strip() if i < len(sp_bpls_str) else ""
                    marr_date = marr_dates[i].strip() if i < len(marr_dates) else ""
                    marr_yr, _ = parse_date(marr_date)

                    sp_row = find_person(sp_name, sp_byr_fallback, people_by_name)
                    if sp_row:
                        w_first = sp_row.get('First Name', '').strip()
                        w_last = sp_row.get('Last Name', '').strip()
                        w_byr, w_bmo = parse_date(sp_row.get('Birth Date', ''))
                        w_bpl = extract_state(sp_row.get('Birth Place', ''))
                        w_fbpl = extract_state(sp_row.get('Father Birth Place', ''))
                        w_mbpl = extract_state(sp_row.get('Mother Birth Place', ''))
                    else:
                        w_first, w_last = split_name(sp_name)
                        w_byr, w_bmo = parse_date(sp_byr_fallback)
                        w_bpl = extract_state(sp_bpl_fallback)
                        w_fbpl, w_mbpl = "", ""

                    if not w_last or '--' in w_last or 'Hidden' in w_last or '[' in w_last:
                        continue

                    h_first, h_last, h_byr, h_bmo, h_bpl, h_fbpl, h_mbpl = p1_first, p1_last, p1_byr, p1_bmo, p1_bpl, p1_fbpl, p1_mbpl

                    couple_key = f"{h_first}_{h_last}_{w_first}_{w_last}"
                    if couple_key not in seen_couples:
                        records.append([
                            h_first, h_last, h_byr, h_bmo, h_bpl, h_fbpl, h_mbpl,
                            w_first, w_last, w_byr, w_bmo, w_bpl, w_fbpl, w_mbpl,
                            marr_yr, num_children
                        ])
                        seen_couples.add(couple_key)
            elif not spouses_str:
                # Lone wolf
                if p1_sex == 'M':
                    records.append([
                        p1_first, p1_last, p1_byr, p1_bmo, p1_bpl, p1_fbpl, p1_mbpl,
                        "", "", "", "", "", "", "",
                        "", 0
                    ])
                else:
                    records.append([
                        "", "", "", "", "", "", "",
                        p1_first, p1_last, p1_byr, p1_bmo, p1_bpl, p1_fbpl, p1_mbpl,
                        "", 0
                    ])

    logger.info(f"  -> Extracted {len(records)} nuclear family units!")

    headers = [
        'h_first', 'h_last', 'h_byr', 'h_bmo', 'h_bpl', 'h_fbpl', 'h_mbpl',
        'w_first', 'w_last', 'w_byr', 'w_bmo', 'w_bpl', 'w_fbpl', 'w_mbpl',
        'marr_yr', 'num_children'
    ]
    with open(couples_csv, 'w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        writer.writerow(headers)
        writer.writerows(records)


if __name__ == "__main__":
    main_logger = gen_logging.setup_logging("GEDCOM_PARSER")

    input_dir = os.path.join(project_root, "gedcom_sources")
    input_files = [f for f in os.listdir(input_dir) if f.endswith("_individuals.csv")]

    input_file = os.path.join(input_dir, input_files[0]) if input_files else os.path.join(input_dir,
                                                                                          "gedcom_individuals.csv")

    couples_csv_file = os.path.join(project_root, "gedcom_sources", "ftm_couples.csv")
    convert_gedcom_csv(input_file, couples_csv_file, main_logger)
